const markets=[["Bitcoin","BTC","67 420,10 €","+2,84%",67420.10],["Ethereum","ETH","3 248,70 €","+1,92%",3248.70],["Solana","SOL","154,20 €","+4,31%",154.20],["USD Coin","USDC","0,92 €","+0,01%",0.92],["Chainlink","LINK","17,84 €","-0,73%",17.84],["Avalanche","AVAX","28,16 €","+1,48%",28.16]];
const API=localStorage.getItem("bitgold-api")||"http://localhost:3000";const apiToken=localStorage.getItem("bitgold-token")||"";const state=JSON.parse(localStorage.getItem("bitgold-demo")||'{"cash":10000,"holdings":{"BTC":0,"ETH":0,"SOL":0}}');let tradeSide="buy";let authMode="login";
document.getElementById("marketGrid").innerHTML=markets.map(([name,symbol,price,change])=>`<article class="market"><div><strong>${name}</strong> <span class="symbol">${symbol}</span></div><div class="price">${price}</div><div class="${change.startsWith("-")?"symbol":"positive"}">${change}</div><button class="btn btn-ghost market-btn" onclick="openTrade('buy','${symbol}')">Acheter</button></article>`).join("");
function save(){localStorage.setItem("bitgold-demo",JSON.stringify(state));renderWallet()}
function renderWallet(){document.getElementById("cashBalance").textContent=state.cash.toLocaleString("fr-FR",{minimumFractionDigits:2})+" €";document.getElementById("holdings").innerHTML=["BTC","ETH","SOL"].map(s=>`<div class="holding"><span>${s}</span><strong>${state.holdings[s].toFixed(6)}</strong></div>`).join("")}
function simulate(){const amount=Number(document.getElementById("amount").value||0);const asset=document.getElementById("asset").value;const rates={"Bitcoin (BTC)":1.2842,"Ethereum (ETH)":1.192,"Solana (SOL)":1.431};const gain=amount*(rates[asset]-1);document.getElementById("result").textContent=`Simulation : ${amount.toLocaleString("fr-FR")} € en ${asset} → estimation théorique ${(amount+gain).toLocaleString("fr-FR",{maximumFractionDigits:2})} € après une variation hypothétique. Gain/perte : ${gain.toLocaleString("fr-FR",{maximumFractionDigits:2})} €.`}
function openTrade(side,asset="BTC"){tradeSide=side;document.getElementById("tradeTitle").textContent=side==="buy"?"Acheter des cryptos":"Vendre des cryptos";document.getElementById("tradeAsset").value=asset;document.getElementById("tradeResult").textContent="";document.getElementById("tradeModal").hidden=false}
function closeTrade(){document.getElementById("tradeModal").hidden=true}
function executeTrade(){const asset=document.getElementById("tradeAsset").value;const amount=Number(document.getElementById("tradeAmount").value||0);const prices={BTC:67420.10,ETH:3248.70,SOL:154.20};const units=amount/prices[asset];if(amount<=0)return;if(tradeSide==="buy"){if(amount>state.cash){document.getElementById("tradeResult").textContent="Solde démo insuffisant.";return}state.cash-=amount;state.holdings[asset]+=units}else{if(units>state.holdings[asset]){document.getElementById("tradeResult").textContent="Quantité démo insuffisante.";return}state.cash+=amount;state.holdings[asset]-=units}save();document.getElementById("tradeResult").textContent=`Opération démo effectuée : ${tradeSide==="buy"?"achat":"vente"} de ${units.toFixed(6)} ${asset} pour ${amount.toFixed(2)} €.`}
function openModal(type){authMode=type==="inscription"?"signup":"login";document.getElementById("modalTitle").textContent=authMode==="signup"?"Créer un compte BitGold":"Connexion BitGold";document.getElementById("authSubmit").textContent=authMode==="signup"?"Créer mon compte":"Se connecter";document.getElementById("authSwitch").textContent=authMode==="signup"?"J'ai déjà un compte":"Créer un compte";document.getElementById("authResult").textContent="";document.getElementById("modal").hidden=false}
function switchAuth(){openModal(authMode==="signup"?"connexion":"inscription")}
async function submitAuth(){const email=document.getElementById("authEmail").value,password=document.getElementById("authPassword").value;try{const r=await fetch(API+"/api/auth/"+(authMode==="signup"?"signup":"login"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.error||"Erreur");localStorage.setItem("bitgold-token",d.token);document.getElementById("authResult").textContent="Compte connecté.";document.getElementById("authState").textContent="Connecté";setTimeout(closeModal,500)}catch(e){document.getElementById("authResult").textContent=e.message}}
function closeModal(){document.getElementById("modal").hidden=true}
renderWallet();