import {useCallback,useEffect,useState} from "react";
export type Position={asset:string;quantity:number;price:number;value:number;allocation:number};
export type Dashboard={updatedAt:number;portfolio:{cash:number;invested:number;total:number;returnEur:number;returnPct:number;positions:Position[]};risk:{score:number;label:string;activeBots:number};subscription:{label:string};market:{regime:string};activity:{bot_type:string;action:string;asset:string|null;message:string;created_at:string}[];integrity:{ok:boolean}};
export type Analytics={performance:{points:{date:string;total:number}[]}};
type State={status:"guest"|"loading"|"ready"|"error"|"expired";dashboard?:Dashboard;analytics?:Analytics;error?:string};
const demoDashboard:Dashboard={updatedAt:Date.now(),portfolio:{cash:7250,invested:2750,total:10000,returnEur:0,returnPct:0,positions:[{asset:"BTC",quantity:0.02,price:67500,value:1350,allocation:13.5},{asset:"ETH",quantity:0.3,price:3200,value:960,allocation:9.6},{asset:"SOL",quantity:2.8,price:157.14,value:440,allocation:4.4}]},risk:{score:24,label:"Modéré",activeBots:1},subscription:{label:"Démo"},market:{regime:"simulation"},activity:[],integrity:{ok:true}};
const demoAnalytics:Analytics={performance:{points:[{date:"J-5",total:9800},{date:"J-4",total:9860},{date:"J-3",total:9780},{date:"J-2",total:9930},{date:"J-1",total:10040},{date:"Aujourd’hui",total:10000}]}};
function demoMode(){try{return new URLSearchParams(window.location.search).get("testmode")==="1"}catch{return false}};
function token(){try{return localStorage.getItem("bitgold-token")||""}catch{return ""}}
async function request<T>(path:string,bearer:string,signal:AbortSignal):Promise<T>{const response=await fetch(path,{signal,headers:{Authorization:`Bearer ${bearer}`,Accept:"application/json"}});if(response.status===401)throw new Error("SESSION_EXPIRED");if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(typeof data.error==="string"?data.error:`Erreur API (${response.status})`)}return response.json() as Promise<T>}
export function useBitGoldDashboard(){const [version,setVersion]=useState(0);const [state,setState]=useState<State>({status:"loading"});const refresh=useCallback(()=>setVersion(v=>v+1),[]);
useEffect(()=>{if(demoMode()){setState({status:"ready",dashboard:demoDashboard,analytics:demoAnalytics});return}const bearer=token();if(!bearer){setState({status:"guest"});return}const controller=new AbortController();setState({status:"loading"});Promise.all([request<Dashboard>("/api/dashboard",bearer,controller.signal),request<Analytics>("/api/dashboard/analytics",bearer,controller.signal)]).then(([dashboard,analytics])=>{if(!controller.signal.aborted)setState({status:"ready",dashboard,analytics})}).catch((error:unknown)=>{if(controller.signal.aborted)return;const message=error instanceof Error?error.message:"Erreur inconnue";if(message==="SESSION_EXPIRED"){try{localStorage.removeItem("bitgold-token")}catch{}setState({status:"expired"})}else setState({status:"error",error:message})});return()=>controller.abort()},[version]);
return {...state,refresh}}
